sudo: required
dist: trusty
language: node_js
env: TRAVIS_CI=true
addons:
  firefox: "latest"
  chrome: stable
script:
  - npm run unit
  - npm run e2e
node_js:
  - "7.7.1"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5
after_script:
  - "sh -e /etc/init.d/xvfb stop"
